-- Initial schema for Gamio backend

-- Users created on first Google sign-in
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  google_sub TEXT UNIQUE NOT NULL,
  email TEXT NOT NULL,
  display_name TEXT NOT NULL DEFAULT 'Player',
  avatar_url TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 3 daily seeds generated by cron job
CREATE TABLE IF NOT EXISTS daily_seeds (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT UNIQUE NOT NULL,
  seed_a TEXT NOT NULL,
  seed_b TEXT NOT NULL,
  seed_c TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Which seed each user was assigned on which day
CREATE TABLE IF NOT EXISTS daily_assignments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL REFERENCES users(id),
  seed_id INTEGER NOT NULL REFERENCES daily_seeds(id),
  seed_index INTEGER NOT NULL CHECK(seed_index IN (0,1,2)),
  assigned_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(user_id, seed_id)
);

-- Individual puzzle completions within a daily challenge set
CREATE TABLE IF NOT EXISTS puzzle_completions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL REFERENCES users(id),
  assignment_id INTEGER NOT NULL REFERENCES daily_assignments(id),
  puzzle_index INTEGER NOT NULL CHECK(puzzle_index >= 0),
  game_type TEXT NOT NULL,
  time_seconds REAL NOT NULL CHECK(time_seconds > 0),
  completed_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Overall daily challenge record (total time across all puzzles)
CREATE TABLE IF NOT EXISTS daily_completions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL REFERENCES users(id),
  assignment_id INTEGER UNIQUE NOT NULL REFERENCES daily_assignments(id),
  seed_id INTEGER NOT NULL REFERENCES daily_seeds(id),
  total_time_seconds REAL NOT NULL CHECK(total_time_seconds > 0),
  streak_count INTEGER NOT NULL DEFAULT 0,
  completed_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(user_id, seed_id)
);

-- User streaks
CREATE TABLE IF NOT EXISTS streaks (
  user_id TEXT PRIMARY KEY REFERENCES users(id),
  current_streak INTEGER NOT NULL DEFAULT 0,
  longest_streak INTEGER NOT NULL DEFAULT 0,
  last_completed_date TEXT,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Leaderboard view for fast queries
CREATE INDEX IF NOT EXISTS idx_daily_completions_seed_time
  ON daily_completions(seed_id, total_time_seconds);

CREATE INDEX IF NOT EXISTS idx_daily_completions_user
  ON daily_completions(user_id);

CREATE INDEX IF NOT EXISTS idx_puzzle_completions_assignment
  ON puzzle_completions(assignment_id);
